services:
  api:
    image: amineelgaini/online-shop-api
    build:
      context: .
      target: test
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: test
      MONGO_URI: mongodb://root:password@mongo:27017/testDb
      SECRET: secret
      PORT: 8000
    depends_on:
      - mongo
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        
        - path: ./
          target: /app
          action: sync
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_AUTH_USERNAME=root
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
        depends_on:
            - mongo
        ports:
          - "9090:8081"
  
volumes:
  mongo-db: